### ISSUE TITLE
نحوه تعریف اپلیکیشن با پلتفرم ریکت نیتیو

### ISSUE THREAD

**Issue by mahshadalishahi** [chabokpush/chabok-rn-chat#1]
سلام
من میخوام اپلیکیشنمو که با پلتفرم ریکت نیتیو درست شده رو بهچابک متصل کنم اما در پنل کاربری چابک در بخش پلتفرم ها پلتفرم ریکت موجود نیست

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">بهچابک متصل کنم اما در پنل کاربری چابک در بخش پلتفرم ها پلتفرم ریکت موجود</p>
</blockquote>
<p dir="rtl"><a href="https://doc.chabokpush.com/panel/settings.html#%D9%BE%D9%84%D8%AA%D9%81%D8%B1%D9%85%D9%87%D8%A7">پلتفرم‌هایی که در پنل در بخش تنظیمات مشاهده می‌کنید</a> برای تنظیم پوش‌نوتیفیکیشن اندروید،  iOS، ویندوز و وب هست.</p>
<p dir="rtl">برای ارسال پوش نیازی نیست تنظیمات ریکت‌نیتوی انجام بدید چون ریکت‌نیتو یک فریمورک برای ساخت اپلیکیشن اندروید، iOS و ویندوز هست. پس با تنظیم کردن پوش‌نوتیفکیشن اندروید و iOS شما می‌تونین روی پلتفرمی که اپلیکیشن رو اجرا گرفتین پوش دریافت کنین</p>
<p dir="rtl">چابک دو کتابخانه ریکت‌نیتو داره:</p>
<ol dir="rtl">
<li dir="rtl"><p dir="rtl"><a href="https://doc.chabokpush.com/react-native/introducing.html">PureJs</a> : که کد پوش ساپورت هست و هیچ کد نیتوی در این کتابخانه وجود نداره. </p>
</li>
<li dir="rtl"><p dir="rtl"><a href="https://doc.chabokpush.com/react-native-bridge/introducing.html">NativeBridge</a>: این کتابخانه یک bridge رو کتابخانه‌های نیتو اندروید و iOS ما هست.</p>
</li>
</ol>

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا issue خودتون رو تو ریپازیتوری مرتبط مطرح کنید.</p>
<p dir="rtl"><a href="https://github.com/chabokpush/chabok-client-rn-js/issues">ریپازیتوری ReactNative PureJs
</a></p>
<p dir="rtl"><a href="https://github.com/chabokpush/chabok-client-rn/issues">ریپازیتوری ReactNative NativeBridge</a></p>
